### PR TITLE
Added sausage recipe

### PR DESCRIPTION
**Pull request by jmjarvi**
No comments

### CODE REVIEW

**Comment by tprossi** [comment]
Hi, could you check the error `file sausage_recipe.md contains no string 'taco'`?

**Comment by jmjarvi** [comment]
It's fixed now, this will close issue no. #8

**Comment by tprossi** [comment]
Do you mean issue #3?

**Comment by tprossi** [comment]
Note that now #3 says "tprossi mentioned this issue now "

**Pull request merged**
